-- MatchKit database schema.
-- Run once in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.
-- Then run seed.sql (generated by `npm run catalog:sql`).

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------

create table if not exists public.leagues (
  id          serial primary key,
  slug        text not null unique,
  name        text not null,
  short_name  text not null,
  logo_path   text,                  -- path inside the "matchkit" storage bucket
  sort_order  int  not null default 0
);

create table if not exists public.clubs (
  id         serial primary key,
  league_id  int  not null references public.leagues(id) on delete cascade,
  slug       text not null unique,
  name       text not null,
  logo_path  text
);

create table if not exists public.products (
  id          serial primary key,
  club_id     int  not null references public.clubs(id) on delete cascade,
  slug        text not null unique,
  name        text not null,
  kit_type    text not null check (kit_type in ('home', 'away', 'third')),
  season      text not null default '2026/27',
  price       int  not null check (price > 0),   -- whole Naira
  description text,
  is_featured boolean not null default false,
  created_at  timestamptz not null default now()
);

create table if not exists public.product_images (
  id          serial primary key,
  product_id  int  not null references public.products(id) on delete cascade,
  path        text not null,
  position    int  not null default 0
);

create table if not exists public.product_sizes (
  product_id  int  not null references public.products(id) on delete cascade,
  size        text not null check (size in ('S', 'M', 'L', 'XL', 'XXL')),
  in_stock    boolean not null default true,
  primary key (product_id, size)
);

create index if not exists clubs_league_idx on public.clubs(league_id);
create index if not exists products_club_idx on public.products(club_id);
create index if not exists product_images_product_idx on public.product_images(product_id);

-- ---------------------------------------------------------------------------
-- Users (Supabase Auth owns auth.users; profiles holds shop details)
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text,
  full_name   text,
  phone       text,
  created_at  timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Cart and wishlist
-- ---------------------------------------------------------------------------

create table if not exists public.cart_items (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  product_id  int  not null references public.products(id) on delete cascade,
  size        text not null check (size in ('S', 'M', 'L', 'XL', 'XXL')),
  quantity    int  not null check (quantity between 1 and 20),
  created_at  timestamptz not null default now(),
  unique (user_id, product_id, size)
);

create table if not exists public.wishlist_items (
  user_id     uuid not null references auth.users(id) on delete cascade,
  product_id  int  not null references public.products(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (user_id, product_id)
);

-- ---------------------------------------------------------------------------
-- Orders
-- ---------------------------------------------------------------------------

create table if not exists public.orders (
  id              uuid primary key default gen_random_uuid(),
  order_number    text not null unique,
  user_id         uuid not null references auth.users(id),
  customer_name   text not null,
  email           text not null,
  phone           text not null,
  address         text not null,
  city            text not null,
  state           text not null,
  subtotal        int  not null,
  total           int  not null,
  status          text not null default 'placed',
  created_at      timestamptz not null default now()
);

create table if not exists public.order_items (
  id            serial primary key,
  order_id      uuid not null references public.orders(id) on delete cascade,
  product_id    int  references public.products(id) on delete set null,
  product_name  text not null,
  club_name     text not null,
  kit_type      text not null,
  image_path    text,
  size          text not null,
  quantity      int  not null check (quantity > 0),
  unit_price    int  not null,
  line_total    int  not null
);

create index if not exists orders_user_idx on public.orders(user_id);
create index if not exists order_items_order_idx on public.order_items(order_id);

-- place_order: creates an order from the caller's cart in one transaction.
-- Prices come from the products table, never from the browser.
create or replace function public.place_order(
  p_customer_name text,
  p_email text,
  p_phone text,
  p_address text,
  p_city text,
  p_state text
) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid();
  v_order uuid;
  v_subtotal int;
  v_number text;
begin
  if v_user is null then
    raise exception 'Not signed in';
  end if;

  select coalesce(sum(p.price * c.quantity), 0) into v_subtotal
  from cart_items c join products p on p.id = c.product_id
  where c.user_id = v_user;

  if v_subtotal = 0 then
    raise exception 'Cart is empty';
  end if;

  v_number := 'MK-' || to_char(now(), 'YYMMDD') || '-' || upper(substr(md5(gen_random_uuid()::text), 1, 5));

  insert into orders (order_number, user_id, customer_name, email, phone, address, city, state, subtotal, total)
  values (v_number, v_user, p_customer_name, p_email, p_phone, p_address, p_city, p_state, v_subtotal, v_subtotal)
  returning id into v_order;

  insert into order_items (order_id, product_id, product_name, club_name, kit_type, image_path, size, quantity, unit_price, line_total)
  select v_order, p.id, p.name, cl.name, p.kit_type,
         (select i.path from product_images i where i.product_id = p.id order by i.position limit 1),
         c.size, c.quantity, p.price, p.price * c.quantity
  from cart_items c
  join products p on p.id = c.product_id
  join clubs cl on cl.id = p.club_id
  where c.user_id = v_user;

  delete from cart_items where user_id = v_user;

  return v_order;
end;
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.leagues        enable row level security;
alter table public.clubs          enable row level security;
alter table public.products       enable row level security;
alter table public.product_images enable row level security;
alter table public.product_sizes  enable row level security;
alter table public.profiles       enable row level security;
alter table public.cart_items     enable row level security;
alter table public.wishlist_items enable row level security;
alter table public.orders         enable row level security;
alter table public.order_items    enable row level security;

-- Catalog is public to read.
drop policy if exists "public read" on public.leagues;
create policy "public read" on public.leagues for select using (true);
drop policy if exists "public read" on public.clubs;
create policy "public read" on public.clubs for select using (true);
drop policy if exists "public read" on public.products;
create policy "public read" on public.products for select using (true);
drop policy if exists "public read" on public.product_images;
create policy "public read" on public.product_images for select using (true);
drop policy if exists "public read" on public.product_sizes;
create policy "public read" on public.product_sizes for select using (true);

-- Users manage only their own rows.
drop policy if exists "own profile" on public.profiles;
create policy "own profile" on public.profiles for all
  using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "own cart" on public.cart_items;
create policy "own cart" on public.cart_items for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own wishlist" on public.wishlist_items;
create policy "own wishlist" on public.wishlist_items for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Orders are read-only to their owner; they are written by place_order().
drop policy if exists "own orders" on public.orders;
create policy "own orders" on public.orders for select using (auth.uid() = user_id);

drop policy if exists "own order items" on public.order_items;
create policy "own order items" on public.order_items for select
  using (exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- Storage: public bucket for logos and jersey images
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('matchkit', 'matchkit', true)
on conflict (id) do nothing;
